name = "multiplayer-game-v2"  # Debe coincidir con el Worker en Cloudflare
main = "worker.js"             # O "worker.js", según el nombre de tu archivo
compatibility_date = "2023-01-01"
account_id = "1f9c1c5f7652f87a70ef146cefee9308"  # Tu account ID del error
